---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-controller
  namespace: rh-kb-chatbot
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-controller-binding
  namespace: rh-kb-chatbot
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: rh-kb-chatbot-doc-ingestion
roleRef:
  kind: Role
  name: rollout-controller
  apiGroup: rbac.authorization.k8s.io
