FROM registry.access.redhat.com/ubi9/nodejs-18

USER root

RUN yum -y update && \
    yum clean all

COPY --chown=1001:0 . /tmp/src

USER 1001

RUN /usr/libexec/s2i/assemble

CMD /usr/libexec/s2i/run
